# Generated by Django 5.2.6 on 2025-09-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_venue_delete_client_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.venue', verbose_name='Venue')),
            ],
        ),
    ]
