# Generated by Django 5.2.6 on 2025-09-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('genre', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('royalty_rate', models.IntegerField(verbose_name='Royalty rate %')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.event', verbose_name='Event')),
            ],
        ),
    ]
