# Generated by Django 5.2.6 on 2025-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0004_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('artist_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second name')),
                ('ticket_type', models.CharField(choices=[('Table', '100K'), ('VIP', '50K'), ('Platinum', '25K'), ('Ordinary', '10K')], max_length=50, verbose_name='Ticket')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.event', verbose_name='Event')),
            ],
        ),
    ]
