# Generated by Django 5.2.6 on 2025-09-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0005_eventartist_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventartist',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='eventartist',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.event', verbose_name='Event'),
        ),
    ]
