# Generated by Django 5.2.6 on 2025-10-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0007_alter_event_date_alter_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
