# Generated by Django 5.2.6 on 2025-10-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0008_rename_frist_name_artist_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='event',
        ),
    ]
